apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecom-backend.fullname" . }}
  labels: {{- include "ecom-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "ecom-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ecom-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
