name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecom-backend/ecom-backend:$GITHUB_SHA .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecom-backend/ecom-backend:$GITHUB_SHA

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_CLUSTER_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}

    # - name: Deploy to GKE
    #   run: |
    #     kubectl set image deployment/ecom-backend ecom-backend=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecom-backend:$GITHUB_SHA
    #     kubectl rollout status deployment/ecom-backend

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install ecom-backend helm/ecom-backend --set image.tag=$GITHUB_SHA